config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sessions#welcome'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  delete '/logout' => 'sessions#destroy'
  get '/latest_shoes' => 'shoes#latest_shoes'
  get "/shoes/search", to: "shoes#search"
  get "/shoes/jordan/4" => 'shoes#jordan'

  get '/auth/google_oauth2/callback' => 'sessions#omniauth' 


  resources :reviews
  resources :shoes do
    resources :reviews , only:  [:new, :index]
  end
  resources :brands
  resources :users, only: [:show, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
    has_many :shoes
    validates :name, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shoe

  validates :title, presence: true
  validates :heat, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than: 11}
  validates :shoe, uniqueness: { scope: :user, message: "You already reviewed these kicks"}
end

app/models/shoe.rb
class Shoe < ApplicationRecord
  belongs_to :brand
  belongs_to :user
  has_many :reviews
  has_many :users, through: :reviews
  #accepts_nested_attributes_for :brand

  validates :name, presence: true
  validates :image, presence: true #prevent them from being saved to the database if their data doesn't look right.




  def brand_attributes=(attributes)
    self.brand = Brand.find_or_create_by(attributes) if !attributes['name'].empty? #finds or creates brands by name
    self.brand
  end


  def brand_name #finds brand name
    brand.try(:name)
  end


  def name_and_brand
   "#{name} - #{brand.try(:name)}" #try and find name or brand to display on user homepage
  end

  def self.latest_shoes #5 most recent shoes
    order(created_at: :desc).each_slice(5).first
  end

  def self.search(search) #uses instances to search for a shoe by name
   if search
    @shoe = self.all.select{|shoe|
    shoe.title.include?(search.titleize)}

      if shoe
        self.where(title: @shoe.title)
      else
        @shoe = nil
      end
       else
        @shoe = nil
      end
      @shoe
    end
  end

app/models/user.rb
class User < ApplicationRecord 
    has_many :reviews
    has_many :shoes, through: :reviews

    has_many :kicks
    validates :username, uniqueness: true,  presence: true
    has_secure_password


    def self.create_by_google_omniauth(auth)
        self.find_or_create_by(username: auth[:info][:email]) do |u|
          u.password = SecureRandom.hex
        end
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in? #used in your Rails views to share reusable code

    private

    def logged_in?
        !!session[:user_id] #boolean value
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) #current user is equal to user_id
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in?
    end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
    before_action :redirect_if_not_logged_in


    def index
      @brands = Brand.all
    end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :redirect_if_not_logged_in #runs first before code

    
    def new
    if
        @shoe = Shoe.find_by_id(params[:shoe_id])
        @review = @shoe.reviews.build #allreviews
    else
        @review = Review.new #new
        end
    end

    def create
        @review = current_user.reviews.build(review_params) #new instance in memory
        if @review.save
          redirect_to review_path(@review) #all riviews
            
        elsif
          render :new
        end
      end

    def index
        if @shoe = Shoe.find_by_id(params[:shoe_id]) #nested and shoe id
            @reviews = @shoe.reviews
        else
            #not nested
            @reviews = Review.all #not nested
        end
    end

    def show
        @review = Review.find_by_id(params[:id])
    end

    private #all private, can’t call private methods from outside the class that defines them.
    
    def review_params
        params.require(:review).permit(:shoe_id, :image, :content, :heat, :title)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def welcome
    end

    def new
        @user = User.new
    end

    def create
        @user = User.find_by(username: params[:user][:username])#instance variable
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            flash[:error] = "Sorry wrong username/password"
            redirect_to login_path
        end
    end

    def omniauth
        @user = User.create_by_google_omniauth(auth)
        session[:user_id] = @user.id #logs user in
        redirect_to user_path(@user)
    end


    def destroy
        session.delete(:user_id)
        redirect_to '/'
    end


    private
    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
    before_action :set_shoes, only:[:show, :edit, :update]
    before_action :redirect_if_not_logged_in


    def new
        @shoe = Shoe.new
        @shoe.build_brand
    end

    def create
        @shoe = Shoe.new(shoe_params)#instance variables
        @shoe.user_id = session[:user_id]
        if @shoe.save
            redirect_to shoe_path(@shoe)
        else
          @shoe.build_brand
          render :new
        end
      end

      def index
       if params[:s]
          @shoes = Shoe.where('name LIKE ?', "%#{params[:s]}%")#searches and displays all shoe by name
        else
          @shoes = Shoe.all
      end
    end

      def search
        @shoe = Shoe.search(params[:brand_attributes])
      end

      def show
      end

      def jordan
        @shoes = Shoe.where('name LIKE ? ', "%jordan%")
      end

      def edit
      end

      def update
        if @shoe.update(shoe_params)
          redirect_to shoe_path(@shoe)
        else
          render :edit
      end
    end

    def latest_shoes
      @shoes = Shoe.latest_shoes
    end

    def username
    end

    private

    def shoe_params
        params.require(:shoe).permit(:name, :description, :image, :brand_id, brand_attributes: [:name])#schema
    end

    def set_shoes
        @shoe = Shoe.find_by(id: params[:id])
        redirect_to shoes_path if !@shoe
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)#instance variables
      if @user.save
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      else
        render :new
      end
    end

    def show
      redirect_if_not_logged_in
      @user = User.find_by_id(params[:id])
      redirect_to '/' if !@user
    end

  
    private

    def user_params
        params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def render_nav_bar
      if logged_in?
        render partial: 'layouts/loggedin'
      else
        render partial: 'layouts/loggedout'
      end
    end
  end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/brands/index.html.erb
<h1>All Brands!</h1>

<ol>
  <% @brands.each do |brand| %>
    <li><%= brand.name %></li>
  <% end %>
</ol>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_loggedin.html.erb
    <nav class="navbar navbar-black bg-black">
    <a class="navbar-brand" href="#" class="text-white bg-dark"><%= image_tag("SNBox.png",:size => '50x50') %>
    </a>
    <p class="text-danger">
    <form class="form-inline">
    <button class="btn btn-outline-danger" type="button"><%= link_to "Home", user_path(current_user) %></button> |
    <button class="btn btn-outline-danger" type="button"> <%= link_to "Log Out", logout_path, method: :delete %> |
    <button class="btn btn-outline-danger" type="button"><%= link_to "Add kicks", new_shoe_path %> |
    <button class="btn btn-outline-danger" type="button"><%= link_to "All Brands", brands_path %> |
    <button class="btn btn-outline-danger" type="button"><%= link_to "All Shoes", shoes_path %> |
    <button class="btn btn-outline-danger" type="button"> <%= link_to "All Reviews", reviews_path %> |
    <button class="btn btn-outline-danger" type="button"> <%= link_to "Recent User Shoes", latest_shoes_url %> |
    </form>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SneakerBox</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <div><%= render_nav_bar %></div>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/index.html.erb
<% if @shoe %>
    <h1>Kicks reviewed for <%= @shoe.name %> - <%= @shoe.brand_name%>
<% else %>
    <h1>All Kicks reviewed</h1>
<% end %>


<ol>
<% @reviews.each do |sr| %>

<li> 
<%= sr.shoe.name%> + <%= sr.title %> + <%= sr.heat %>
</li>
<% end %>

</ol>

app/views/reviews/new.html.erb
<%= render partial: 'layouts/errors', locals: {object: @review}  %>


<%= form_for(@review) do |f|%>
  <% if params[:shoes_id] %>
    <%= f.hidden_field :shoes_id %>
  <% else %>
    <div>
      <%= f.label :shoes_id, "Select a shoe" %>
      <%= f.collection_select :shoe_id, Shoe.all, :id, :name, include_blank: true  %>
    </div>
  <% end %>

     <div>
        <%= f.label :heat %>
        <%= f.number_field :heat, min:1, max:10 %>
    </div>

    <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
     <div>
        <%= f.label :content %>
        <%= f.text_area :content, size: "25x10" %>
    </div>
    <%= f.hidden_field :shoe_id %>

    <%= f.submit %>

    <% end %>

app/views/reviews/show.html.erb
<h1><%= @review.title%> - <%= @review.heat%> </h1>

<p><%= @review.content%></p>

app/views/shoes/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @shoe}  %>
<div class="container p-3 my-3 border">
<%= form_with model: @shoe do |f|%>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
  <%= f.label :image %>
    <%= f.text_field :image %>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <br>

  <p> Choose a shoe brand: </p>
  <div>
    <%= f.collection_select :brand_id, Brand.all, :id, :name, include_blank: 'Select One'%>

  </div>

  <p> Or create a new Brand: </p>
  <div>
    <%=f.fields_for :brand do |b| %>
      <%= b.label :name %>
      <%= b.text_field :name %>
    <% end %>
  </div>
  <br>
  <%= f.submit %>
<% end %>
</div>

app/views/shoes/edit.html.erb
<h1>Edit Kicks!</h1>

<%= render partial: 'form'%>

app/views/shoes/index.html.erb
<h1>All the Kicks</h1>

<h4> Search by shoe </h4>
<%= form_tag(shoes_path, method: :get) do %>
<%= label_tag(:s, "search for:") %>
<%= text_field_tag(:s) %>
<%= submit_tag ("Search")%>
<% end %>

<% @shoes.each do |s| %>
  
  <h2><%= link_to s.name, shoe_path(s.id)%> - <%= s.brand.name %> </h2>
  <%= s.description%>
  <br>
  <%= link_to "Write a review", new_shoe_review_path(s) %>
  <div>
     <% end %>
  </div>

app/views/shoes/jordan.html.erb
<h1>this is working</h1>

<% @shoes.each do |s| %>
<h2><%= link_to s.name, shoe_path(s.id)%></h2>
<% end %>

app/views/shoes/latest_shoes.html.erb
<h1>Latest Shoes created: </h1>

 <% @shoes.each do |s| %>
  
  <h2> <%= link_to s.name, shoe_path(s.id)%> - <%= s.brand.name %> | <%= s.user.username.capitalize %> </h2>
  <%= s.description%>
  <br>
  <div>
     <% end %>

app/views/shoes/new.html.erb
<h1>Add Kicks!</h1>

<%= render partial: 'form'%>

app/views/shoes/show.html.erb
<h1><%= @shoe.name%>  </h1>


<h2> <%= @shoe.brand_name %> </h2>
<div>
  <p><%= @shoe.description %></p>
  <%= image_tag @shoe.image %>
</div>


<%= link_to "Edit #{@shoe.name}", edit_shoe_path(@shoe) if @shoe.user == current_user%>

<br>

<%= link_to "See all Reviews", shoe_reviews_path(@shoe) %>

app/views/users/new.html.erb
<h1> Sign up!</h1>

<%= form_for (@user)  do |f|%>
  <%= f.label :username %>
  <%= f.text_field :username %>


  <%= f.label :email %>
  <%= f.text_field :email %>


  <%= f.label :password %>
  <%= f.password_field :password %>


  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h1>Welcome to <%= @user.username%>'s homepage! </h1>

<h3>All the kicks reviewed and in <%=@user.username%>'closet:</h3>
<ul>
  <% @user.shoes.each do |sr|%>
  <li> <%= link_to sr.name_and_brand, shoe_path(sr)%> </li>
  <% end %>
</ul>